// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiqsl8dKCdE8_Zcz54ZzP7_bj5GM48KI8',
    appId: '1:732402343984:web:4ef51d873804cb39564df5',
    messagingSenderId: '732402343984',
    projectId: 'campuscurb-c13b7',
    authDomain: 'campuscurb-c13b7.firebaseapp.com',
    storageBucket: 'campuscurb-c13b7.firebasestorage.app',
    measurementId: 'G-LTW66ZMDS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0YobQ5okWmLvIyFjkkGk_VQKNzt59Ns',
    appId: '1:732402343984:android:b7734cc0363d62bf564df5',
    messagingSenderId: '732402343984',
    projectId: 'campuscurb-c13b7',
    storageBucket: 'campuscurb-c13b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOVp1jj7fRWHtw1xmGV_cgeowxFzy4mm8',
    appId: '1:732402343984:ios:46f814e21ec61349564df5',
    messagingSenderId: '732402343984',
    projectId: 'campuscurb-c13b7',
    storageBucket: 'campuscurb-c13b7.firebasestorage.app',
    iosClientId: '732402343984-2ef22egi4ltl0h6ffsup8150cgvtsgt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOVp1jj7fRWHtw1xmGV_cgeowxFzy4mm8',
    appId: '1:732402343984:ios:46f814e21ec61349564df5',
    messagingSenderId: '732402343984',
    projectId: 'campuscurb-c13b7',
    storageBucket: 'campuscurb-c13b7.firebasestorage.app',
    iosClientId: '732402343984-2ef22egi4ltl0h6ffsup8150cgvtsgt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiqsl8dKCdE8_Zcz54ZzP7_bj5GM48KI8',
    appId: '1:732402343984:web:6edf057b91753b74564df5',
    messagingSenderId: '732402343984',
    projectId: 'campuscurb-c13b7',
    authDomain: 'campuscurb-c13b7.firebaseapp.com',
    storageBucket: 'campuscurb-c13b7.firebasestorage.app',
    measurementId: 'G-01QZYNJKG1',
  );
}
